// <auto-generated />
using System;
using ENSAYO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ENSAYO.Migrations
{
    [DbContext(typeof(EnsayoContext))]
    [Migration("20241112183914_secondGear")]
    partial class secondGear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ENSAYO.Models.Abono", b =>
                {
                    b.Property<int>("IdAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbono"));

                    b.Property<decimal?>("CantAbono")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("FechaAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int");

                    b.HasKey("IdAbono")
                        .HasName("PK__Abono__A4693DA75046CECF");

                    b.HasIndex("IdReserva");

                    b.ToTable("Abono", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.Cliente", b =>
                {
                    b.Property<int>("NroDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroDocumento"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Celular")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Contrasena")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Correo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("NroDocumento")
                        .HasName("PK__Clientes__CC62C91CBF5C3D4F");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdTipoDocumento");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ENSAYO.Models.DetalleReservaPaquete", b =>
                {
                    b.Property<int>("DetalleReservaPaquete1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleReservaPaquete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleReservaPaquete1"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int");

                    b.HasKey("DetalleReservaPaquete1")
                        .HasName("PK__DetalleR__2E8BFF2543E3F05D");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdReserva");

                    b.ToTable("DetalleReservaPaquete", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.DetalleReservaServicio", b =>
                {
                    b.Property<int>("IdDetalleReservaServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleReservaServicio"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleReservaServicio")
                        .HasName("PK__DetalleR__D3D91A5A27D05290");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdServicio");

                    b.ToTable("DetalleReservaServicio", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.EstadosReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("NombreEstadoReserva")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdEstadoReserva")
                        .HasName("PK__EstadosR__3E654CA8A077A052");

                    b.ToTable("EstadosReserva", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.Habitacione", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("IdTipoHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("NombreHabitacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitaci__8BBBF90198C62D49");

                    b.HasIndex("IdTipoHabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenAbono", b =>
                {
                    b.Property<int>("IdImagenAbono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenAbono"));

                    b.Property<int?>("IdAbono")
                        .HasColumnType("int");

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.HasKey("IdImagenAbono")
                        .HasName("PK__ImagenAb__A40FAE53ACB5656E");

                    b.HasIndex("IdAbono");

                    b.HasIndex("IdImagen");

                    b.ToTable("ImagenAbono", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenHabitacion", b =>
                {
                    b.Property<int>("IdImagenHabi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenHabi"));

                    b.Property<int?>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.HasKey("IdImagenHabi")
                        .HasName("PK__ImagenHa__5B5FF6ADD722B4AB");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdImagen");

                    b.ToTable("ImagenHabitacion", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenPaquete", b =>
                {
                    b.Property<int>("IdImagenPaque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenPaque"));

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.HasKey("IdImagenPaque")
                        .HasName("PK__ImagenPa__AD53DF94487CC4D2");

                    b.HasIndex("IdImagen");

                    b.HasIndex("IdPaquete");

                    b.ToTable("ImagenPaquete", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenServicio", b =>
                {
                    b.Property<int>("IdImagenServi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagenServi"));

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdImagenServi")
                        .HasName("PK__ImagenSe__3C03784C52F16FFB");

                    b.HasIndex("IdImagen");

                    b.HasIndex("IdServicio");

                    b.ToTable("ImagenServicio", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.Imagene", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImagen")
                        .HasName("PK__Imagenes__B42D8F2AFDCD8D32");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("ENSAYO.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("NomMetodoPago")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdMetodoPago")
                        .HasName("PK__MetodoPa__6F49A9BE678EA3DC");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.Paquete", b =>
                {
                    b.Property<int>("IdPaquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaquete"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("NomPaquete")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPaquete")
                        .HasName("PK__Paquetes__DE278F8BB7831F40");

                    b.HasIndex("IdHabitacion");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("ENSAYO.Models.PaqueteServicio", b =>
                {
                    b.Property<int>("IdPaqueteServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaqueteServicio"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("IdPaquete")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.HasKey("IdPaqueteServicio")
                        .HasName("PK__PaqueteS__DE5C2BC23DCF499F");

                    b.HasIndex("IdPaquete");

                    b.HasIndex("IdServicio");

                    b.ToTable("PaqueteServicio", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("NomPermiso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPermiso")
                        .HasName("PK__Permisos__0D626EC8262DDC90");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ENSAYO.Models.PermisosRole", b =>
                {
                    b.Property<int>("IdPermisosRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermisosRoles"));

                    b.Property<int?>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdPermisosRoles")
                        .HasName("PK__Permisos__8C257ED975284C72");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol");

                    b.ToTable("PermisosRoles");
                });

            modelBuilder.Entity("ENSAYO.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("('1')");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("IVA");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("NroDocumentoCliente")
                        .HasColumnType("int");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reservas__0E49C69DE9D498A9");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("MetodoPago");

                    b.HasIndex("NroDocumentoCliente");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ENSAYO.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NomRol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584C02AAEBC4");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ENSAYO.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdTipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("NomServicio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__2DCCF9A2596EFC75");

                    b.HasIndex("IdTipoServicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("ENSAYO.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("NomTipoDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoDocumento")
                        .HasName("PK__TipoDocu__3AB3332F9ADCBAAC");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("ENSAYO.Models.TipoHabitacione", b =>
                {
                    b.Property<int>("IdTipoHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoHabitacion"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreTipoHabitacion")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("NumeroPersonas")
                        .HasColumnType("int");

                    b.HasKey("IdTipoHabitacion")
                        .HasName("PK__TipoHabi__AB75E87C7AB1133E");

                    b.ToTable("TipoHabitaciones");
                });

            modelBuilder.Entity("ENSAYO.Models.TipoServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("NombreTipoServicio")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdTipoServicio")
                        .HasName("PK__TipoServ__E29B3EA7E4675266");

                    b.ToTable("TipoServicios");
                });

            modelBuilder.Entity("ENSAYO.Models.Abono", b =>
                {
                    b.HasOne("ENSAYO.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Abonos")
                        .HasForeignKey("IdReserva")
                        .HasConstraintName("FK__Abono__IdReserva__75A278F5");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.Cliente", b =>
                {
                    b.HasOne("ENSAYO.Models.Role", "IdRolNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Clientes__IdRol__5EBF139D");

                    b.HasOne("ENSAYO.Models.TipoDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento")
                        .HasConstraintName("FK__Clientes__IdTipo__5FB337D6");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.DetalleReservaPaquete", b =>
                {
                    b.HasOne("ENSAYO.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__DetalleRe__IdPaq__70DDC3D8");

                    b.HasOne("ENSAYO.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleReservaPaquetes")
                        .HasForeignKey("IdReserva")
                        .HasConstraintName("FK__DetalleRe__IdRes__71D1E811");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.DetalleReservaServicio", b =>
                {
                    b.HasOne("ENSAYO.Models.Reserva", "IdReservaNavigation")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("IdReserva")
                        .HasConstraintName("FK__DetalleRe__IdRes__6E01572D");

                    b.HasOne("ENSAYO.Models.Servicio", "IdServicioNavigation")
                        .WithMany("DetalleReservaServicios")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK__DetalleRe__IdSer__6D0D32F4");

                    b.Navigation("IdReservaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.Habitacione", b =>
                {
                    b.HasOne("ENSAYO.Models.TipoHabitacione", "IdTipoHabitacionNavigation")
                        .WithMany("Habitaciones")
                        .HasForeignKey("IdTipoHabitacion")
                        .HasConstraintName("FK__Habitacio__IdTip__4316F928");

                    b.Navigation("IdTipoHabitacionNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenAbono", b =>
                {
                    b.HasOne("ENSAYO.Models.Abono", "IdAbonoNavigation")
                        .WithMany("ImagenAbonos")
                        .HasForeignKey("IdAbono")
                        .HasConstraintName("FK__ImagenAbo__IdAbo__797309D9");

                    b.HasOne("ENSAYO.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenAbonos")
                        .HasForeignKey("IdImagen")
                        .HasConstraintName("FK__ImagenAbo__IdIma__787EE5A0");

                    b.Navigation("IdAbonoNavigation");

                    b.Navigation("IdImagenNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenHabitacion", b =>
                {
                    b.HasOne("ENSAYO.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("ImagenHabitacions")
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ImagenHab__IdHab__46E78A0C");

                    b.HasOne("ENSAYO.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenHabitacions")
                        .HasForeignKey("IdImagen")
                        .HasConstraintName("FK__ImagenHab__IdIma__45F365D3");

                    b.Navigation("IdHabitacionNavigation");

                    b.Navigation("IdImagenNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenPaquete", b =>
                {
                    b.HasOne("ENSAYO.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenPaquetes")
                        .HasForeignKey("IdImagen")
                        .HasConstraintName("FK__ImagenPaq__IdIma__5535A963");

                    b.HasOne("ENSAYO.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("ImagenPaquetes")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__ImagenPaq__IdPaq__5629CD9C");

                    b.Navigation("IdImagenNavigation");

                    b.Navigation("IdPaqueteNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.ImagenServicio", b =>
                {
                    b.HasOne("ENSAYO.Models.Imagene", "IdImagenNavigation")
                        .WithMany("ImagenServicios")
                        .HasForeignKey("IdImagen")
                        .HasConstraintName("FK__ImagenSer__IdIma__4E88ABD4");

                    b.HasOne("ENSAYO.Models.Servicio", "IdServicioNavigation")
                        .WithMany("ImagenServicios")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK__ImagenSer__IdSer__4F7CD00D");

                    b.Navigation("IdImagenNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.Paquete", b =>
                {
                    b.HasOne("ENSAYO.Models.Habitacione", "IdHabitacionNavigation")
                        .WithMany("Paquetes")
                        .HasForeignKey("IdHabitacion")
                        .HasConstraintName("FK__Paquetes__IdHabi__52593CB8");

                    b.Navigation("IdHabitacionNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.PaqueteServicio", b =>
                {
                    b.HasOne("ENSAYO.Models.Paquete", "IdPaqueteNavigation")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdPaquete")
                        .HasConstraintName("FK__PaqueteSe__IdPaq__59063A47");

                    b.HasOne("ENSAYO.Models.Servicio", "IdServicioNavigation")
                        .WithMany("PaqueteServicios")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK__PaqueteSe__IdSer__59FA5E80");

                    b.Navigation("IdPaqueteNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.PermisosRole", b =>
                {
                    b.HasOne("ENSAYO.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("IdPermiso")
                        .HasConstraintName("FK__PermisosR__IdPer__3C69FB99");

                    b.HasOne("ENSAYO.Models.Role", "IdRolNavigation")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__PermisosR__IdRol__3B75D760");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.Reserva", b =>
                {
                    b.HasOne("ENSAYO.Models.EstadosReserva", "IdEstadoReservaNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .HasConstraintName("FK__Reservas__IdEsta__693CA210");

                    b.HasOne("ENSAYO.Models.MetodoPago", "MetodoPagoNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("MetodoPago")
                        .HasConstraintName("FK__Reservas__Metodo__6A30C649");

                    b.HasOne("ENSAYO.Models.Cliente", "NroDocumentoClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("NroDocumentoCliente")
                        .HasConstraintName("FK__Reservas__IdEsta__68487DD7");

                    b.Navigation("IdEstadoReservaNavigation");

                    b.Navigation("MetodoPagoNavigation");

                    b.Navigation("NroDocumentoClienteNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.Servicio", b =>
                {
                    b.HasOne("ENSAYO.Models.TipoServicio", "IdTipoServicioNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdTipoServicio")
                        .HasConstraintName("FK__Servicios__IdTip__4BAC3F29");

                    b.Navigation("IdTipoServicioNavigation");
                });

            modelBuilder.Entity("ENSAYO.Models.Abono", b =>
                {
                    b.Navigation("ImagenAbonos");
                });

            modelBuilder.Entity("ENSAYO.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ENSAYO.Models.EstadosReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ENSAYO.Models.Habitacione", b =>
                {
                    b.Navigation("ImagenHabitacions");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("ENSAYO.Models.Imagene", b =>
                {
                    b.Navigation("ImagenAbonos");

                    b.Navigation("ImagenHabitacions");

                    b.Navigation("ImagenPaquetes");

                    b.Navigation("ImagenServicios");
                });

            modelBuilder.Entity("ENSAYO.Models.MetodoPago", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ENSAYO.Models.Paquete", b =>
                {
                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("ImagenPaquetes");

                    b.Navigation("PaqueteServicios");
                });

            modelBuilder.Entity("ENSAYO.Models.Permiso", b =>
                {
                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("ENSAYO.Models.Reserva", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("DetalleReservaPaquetes");

                    b.Navigation("DetalleReservaServicios");
                });

            modelBuilder.Entity("ENSAYO.Models.Role", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("ENSAYO.Models.Servicio", b =>
                {
                    b.Navigation("DetalleReservaServicios");

                    b.Navigation("ImagenServicios");

                    b.Navigation("PaqueteServicios");
                });

            modelBuilder.Entity("ENSAYO.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("ENSAYO.Models.TipoHabitacione", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("ENSAYO.Models.TipoServicio", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
